title: Sam Carey Blog
description: Thoughts on society, ethics, and reform
baseurl: "/blog"
url: ""

markdown: kramdown

collections:
  drafts:
    output: true
    permalink: /drafts/:title/

exclude:
  - README.md
  - posts/
