title: Sam Carey Blog
description: Thoughts on society, ethics, and reform
baseurl: "/blog"
url: ""

markdown: kramdown

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  strip_title: true
  collections: true

collections:
  drafts:
    output: true
    permalink: /drafts/:title/

exclude:
  - README.md
  - posts/
